version: '3.9'

services:
  web:
    image: nginx:1
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx/secrets:/etc/nginx/secrets
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
